In [1]:
pip install -U pandas

Note: you may need to restart the kernel to use updated packages.


In [3]:
# 匯入套件
import numpy as np

In [4]:
# 語法查詢
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [8]:
# 在未完成的語法後面按下 tab 鍵，會開啟自動完成功能 (語法提示) 
np.array

<function numpy.array>

In [7]:
# 0 維陣列
a = np.array(44)
print(a + a)

88


In [9]:
# 一維陣列
a = np.array([0, 1, 2, 3])
# 在 cell 裡面，程式碼最後一行是變數名稱時，可以自動預覽結果
a

array([0, 1, 2, 3])

In [11]:
# 二維陣列
'''
長這個樣子:
arr = [
    [0,1,2], 
    [3,4,5]
]
'''
a = np.array([[0,1,2],[3,4,5]]); a

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
# shape (形狀，以 tuple 格式呈現)
'''
(2, 3) 代表 2 維陣列:
- 有 2 列，每 1 列有 3 個元素，
- 也可看成幾個 row、幾個 column
'''
a.shape

(2, 3)

In [13]:
# ndim (n-dimensions，維度)
a.ndim

2

In [14]:
# dtype (data-type，陣列當中每一個元素的屬性)
a.dtype

dtype('int32')

In [18]:
# 跟 range() 用法一樣
a = np.arange(1, 10, 3); a

array([1, 4, 7])

In [22]:
# 自動判斷資料型態
a = np.array([1,2,3,4], dtype='float64'); a

array([1., 2., 3., 4.])

In [23]:
# 指定陣列每一個資料的資料型態 (指定 float64)
a = np.array([1,2,3.14])
a_ = a.astype(int); a_

array([1, 2, 3])

In [15]:
# np.linspace(): 建立等距陣列的 1 維陣列
a = np.linspace(0.001, 0.01, num=10); a

array([0.001, 0.002, 0.003, 0.004, 0.005, 0.006, 0.007, 0.008, 0.009,
       0.01 ])

In [11]:
a = np.ones((2,4)); a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])