In [1]:
import numpy as np

In [31]:
# 初始化陣列
x = np.array([2, 4, 6, 8, 10])
y = np.array([10, 8, 6, 4, 2])

In [8]:
# 整數與陣列: 加法
a = x / 4;a

array([0.5, 1. , 1.5, 2. , 2.5])

In [12]:
# 陣列加法運算
a = x / y;a

array([0.2, 0.5, 1. , 2. , 5. ])

In [15]:
# 陣列元素平方
A = x**2
B = y**2

In [16]:
A

array([  4,  16,  36,  64, 100])

In [17]:
B

array([100,  64,  36,  16,   4])

In [18]:
# 陣列元素開根號
A = np.sqrt(x)
B = np.sqrt(y)

In [19]:
A

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [20]:
B

array([3.16227766, 2.82842712, 2.44948974, 2.        , 1.41421356])

In [32]:
# 大於
a = x == y; a

array([False, False,  True, False, False])

In [33]:
# 指定索引
x[0]

2

In [41]:
# 切片 (範圍: [start, end-1, step]
x[1:5]

array([ 4,  6,  8, 10])

In [42]:
# 陣列結合
z = np.concatenate((x, y)); z

array([ 2,  4,  6,  8, 10, 10,  8,  6,  4,  2])

In [44]:
# 將陣列元素加入其它陣列
z = np.concatenate((x, [12, 14, 16])); z

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [45]:
# 在陣列指定索引 2 插入元素 9
z = np.insert(x, 2, 9); z

array([ 2,  4,  9,  6,  8, 10])

In [46]:
# 在陣列指定索引 1 跟 3，分別插入元素 7 跟 9
z = np.insert(x, [1,3], [7,9]); z

array([ 2,  7,  4,  6,  9,  8, 10])

In [47]:
# 刪除索引 1 的元素
z = np.delete(x, 1); z

array([ 2,  6,  8, 10])

In [48]:
# 刪除索引 1 和 3 所放置的元素
z = np.delete(x, [1, 3]); z

array([ 2,  6, 10])

In [49]:
# 計算元素總和
c = np.array([1, 3, 5, 7])
d = np.sum(c); d

16

In [50]:
a = np.array([4, 5, 1, 3, 4])
b = np.array([5, 3, 5, 4, 2])
c = np.inner(a, b); c

60

In [52]:
np.inner(a, b) / ((np.inner(a,a) ** 0.5) * (np.inner(b,b) ** 0.5))

0.8247081822488047