In [1]:
import numpy as np

In [20]:
# 建立二維陣列
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

In [17]:
# 與整數的加法運算
a = x>y;a

array([[False, False],
       [False, False]])

In [21]:
# 取得二維陣列某元素內容
x[0, 1]

2

In [23]:
# 設定二維陣列某元素內容
tmp = np.array([
    [5, 5, 6, 6,],
    [3, 3, 1, 2]
])
tmp[1, 2] = 11; tmp

array([[ 5,  5,  6,  6],
       [ 3,  3, 11,  2]])

In [24]:
# 取得 row = 0 的元素
x[0]

array([1, 2])

In [27]:
# 取得 column = 0 的元素
x[:,0]

array([1, 3])

In [28]:
xx = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
])

In [34]:
xx[0,:4]

array([1, 2, 3, 4])

In [35]:
# 取得 row=0:2, column=2:4
xx[0:2, 2:4]

array([[3, 4],
       [7, 8]])

In [40]:
# 取得前 2 個 row 的元素

xx[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
# 取得 row = 1 之後的元素
xx[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
# 建立一維陣列
x1 = np.array([1, 2, 3, 4, 5, 6])

In [43]:
y1 = x1.reshape(2,3); y1

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
# 將 2x3 陣列轉成一維陣列
x2 = y1.ravel(); x2

array([1, 2, 3, 4, 5, 6])

In [45]:
y1.resize(3,2);y1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
a = np.arange(8).reshape(4,2); a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [48]:
b = a.T; b

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [49]:
# np.arange(3) + 5 是否等於 [5,6,7] ?
a = np.arange(3) + 5; a

array([5, 6, 7])

In [50]:
# np.ones((3, 3)) + np.arange(3) 是否等於 [[1,2,3],[1,2,3],[1,2,3]] ?
a = np.ones((3, 3)) + np.arange(3); a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [51]:
# np.arange(3).reshape((3,1)) + np.arange(3) 是否等於 [[0,1,2],[1,2,3],[2,3,4]] ?
a = np.arange(3).reshape((3,1)) + np.arange(3); a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])