In [1]:
import numpy as np

In [2]:
# 一維陣列的「和」 (加總)
np.sum([1,2,3,4])

10

In [3]:
# 二維陣列的「和」 (加總)
np.sum([[1,2],[3,4]])

10

In [11]:
# 二維陣列的「和」，指定軸 (axis) 來計算
np.sum([[1,2,3,4],[5,6,7,8],[9,10,11,12]],axis=1)

array([10, 26, 42])

In [23]:
# around(): 四捨五入到最近的「偶數值」
np.trunc([1.5, 2.5, 1.6, 3.3])

array([1., 2., 1., 3.])

In [26]:
# absolute(): 回傳絕對值
np.absolute([-3, 3])

array([3, 3])

In [27]:
# square(): 回傳平方值
np.square([4, 9])

array([16, 81])

In [28]:
# sqrt(): 回傳平方根
np.sqrt([4, 9])

array([2., 3.])

In [43]:
np.random.seed(42)
a = np.random.rand(4); a

array([0.68423303, 0.44015249, 0.12203823, 0.49517691])

In [70]:
a = np.random.randint(0, 47, size=6); a
b = np.random.randint(0, 9, size=8); b

array([0, 4, 8, 5, 0, 0, 1, 8])

In [59]:
x = np.arange(10)
np.random.shuffle(x)
x

array([1, 9, 7, 3, 0, 6, 2, 4, 5, 8])